# Generated by Django 4.0.4 on 2022-06-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_coursetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetest',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testdb.coursetest')),
            ],
        ),
    ]
