# Generated by Django 4.0.4 on 2022-06-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_alter_coursetest_score_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='amount_of_answers',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('is_right', models.BooleanField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testdb.testquestion')),
            ],
        ),
    ]
