# Generated by Django 4.0.4 on 2022-06-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_testquestion_amount_of_answers_testanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='amount_of_answers',
        ),
        migrations.AddField(
            model_name='coursetest',
            name='amount_of_answers',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
