# Generated by Django 4.0.4 on 2022-06-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_alter_testquestion_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetest',
            name='amount_of_answers',
        ),
    ]
