# Generated by Django 4.0.4 on 2022-06-12 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_remove_coursetest_amount_of_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.testquestion'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
