# Generated by Django 4.0.4 on 2022-06-12 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0010_alter_testanswer_question_alter_testquestion_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='answer',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
