# Generated by Django 4.0.4 on 2022-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0011_alter_testanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
    ]
