# Generated by Django 4.0.4 on 2022-06-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0012_alter_testanswer_is_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='answer',
            field=models.CharField(max_length=200),
        ),
    ]
