# Generated by Django 4.0.4 on 2022-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0014_testquestion_test_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='test_picture',
            field=models.ImageField(blank=True, null=True, upload_to='icons/test_pictures/%Y/%m/%d/'),
        ),
    ]
