# Generated by Django 4.0.4 on 2022-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0017_alter_journaltask_task_alter_journaltest_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='icons/study_materials_pictures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='icons/task_pictures/%Y/%m/%d/'),
        ),
    ]
