# Generated by Django 4.0.4 on 2022-07-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0018_studymaterial_picture_task_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/study_materials_pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='coursetest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.course'),
        ),
        migrations.AlterField(
            model_name='journaltask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.task'),
        ),
        migrations.AlterField(
            model_name='journaltest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.coursetest'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.course'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testdb.coursetest'),
        ),
    ]
