# Generated by Django 4.0.4 on 2022-07-09 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0019_studymaterial_files_alter_coursetest_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltask',
            name='best_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='journaltask',
            name='number_of_attempts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='journaltest',
            name='best_score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='journaltest',
            name='number_of_attempts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/study_materials/'),
        ),
    ]
