# Generated by Django 4.0.4 on 2022-07-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0020_journaltask_best_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaltask',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='journaltask',
            name='number_of_attempts',
        ),
    ]
