version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=learningdb
      - POSTGRES_USER=Tanusha
      - POSTGRES_PASSWORD=28072002TaTa!
    container_name: db
  web:
    tty: true
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=learningdb
      - POSTGRES_USER=Tanusha
      - POSTGRES_PASSWORD=28072002TaTa!
    depends_on:
      - db
